PWD /Users/brick/Desktop/Uni/TeXiS-v1.0/glosstex
INPUT /usr/local/texlive/2018/texmf.cnf
INPUT /usr/local/texlive/2018/texmf-dist/web2c/texmf.cnf
INPUT /usr/local/texlive/2018/texmf-var/web2c/pdftex/latex.fmt
INPUT Makefile.unx
OUTPUT Makefile.log
